name: Build and publish ApiMock

on:
  release:
    types: [published]
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: settings
        env:
          TAG_NAME: eumagnun/meu-site
          PATH_DOCKER_FILE: ./Docker
        run: echo $TAG_NAME $PATH_DOCKER_FILE
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
       
      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash 
        
      - uses: docker/setup-buildx-action@v1         
        
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: $PATH_DOCKER_FILE
          tags: $TAG_NAME :${{ steps.get_version.outputs.VERSION }}
          push: true
