name: Docker Image CI

on:
  release:
    types: [published]
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: docker/setup-buildx-action@v1        
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          registry: "eumagnun"
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
       
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash 
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./Docker 
          tags: eumagnun/meu-site:${{steps.get_version.outputs.VERSION}}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
